### PR TITLE
fixes: orchestrator

### LINKED ISSUE #105: Orchestrator Improvements
Make orchestrator only manage processes and not be blockchain aware.

### PR DESCRIPTION
**Pull request by hamdiallam**
From the walkthrough.
- use the right rpc url
- check to make sure chain id matches
- make l2opsims a private member of the orchestrator
- dont stop close on first error

Some more fixes after fixing some abstractions
Closes #105

### CODE REVIEW

File: orchestrator/orchestrator.go [hunk 1]
```diff
@@ -62,42 +64,43 @@ func (o *Orchestrator) Start(ctx context.Context) error {
...
-	}
-
-	for _, opSim := range o.L2OpSims {
+	for _, opSim := range o.l2OpSims {
 		if err := opSim.Start(ctx); err != nil {
 			return fmt.Errorf("op simulator instance %s failed to start: %w", opSim.Name(), err)
 		}
 	}
 
+	if err := o.WaitUntilAnvilsAreReady(); err != nil {
```
Comment (tremarkley) [inline orchestrator/orchestrator.go:73]: this has to go before the opSim instances are started, otherwise the clocks will drift since the opsim startup triggers transactions on l2 that will mine blocks and start the clock.

**Comment by hamdiallam** [comment]
* **#111** <a href="https://app.graphite.dev/github/pr/ethereum-optimism/supersim/111?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#110** <a href="https://app.graphite.dev/github/pr/ethereum-optimism/supersim/110?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @hamdiallam and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>
