### PR TITLE
fixes: opsim cleanup & closeApp thread through

### LINKED ISSUE #106: Thread through CloseApp to sub processes so things shutdown correctly if there is an issue bringing up a process

### PR DESCRIPTION
**Pull request by hamdiallam**
Close #106 

1. Thread through closeApp to the different modules
2. Move `cross_l2_inbox.go` into `bindings` package
3. Some code cleanup in opsim to reduce LOC

### CODE REVIEW

**Comment by hamdiallam** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/ethereum-optimism/supersim/117?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#117** <a href="https://app.graphite.dev/github/pr/ethereum-optimism/supersim/117?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#114** <a href="https://app.graphite.dev/github/pr/ethereum-optimism/supersim/114?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @hamdiallam and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

File: bindings/cross_l2_inbox.go [hunk 1]
```diff
@@ -0,0 +1,65 @@
+package bindings
```
Comment (jakim929) [inline bindings/cross_l2_inbox.go:1]: not for now but for a future PR we should just include the abigen generated bindings instead of a custom one like this

**Review by jakim929 — APPROVED** [review]

File: bindings/cross_l2_inbox.go (hunk 1 above)
Comment (hamdiallam) [reply bindings/cross_l2_inbox.go:1]: yea i agree. I was going down that path but left that off till later since it's not the most important
